version: '2'
services:
 mongodb:
   image: mongo:3.3   
   expose:                 # expose ports without publishing to host machine,
     - "27017" #only accessible to linked services, can specify only internal			# port 
#   volumes:
#    - /mnt/db:/data/db
   environment:    
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   image: teamcloudyuga/rsvpapp
   ports:
    - "5000:5000"
   environment:
    MONGODB_HOST: mongodb
   networks:
    - rsvpnet

networks:
  rsvpnet:
