apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
      - name: rsvp-app 
        image: teamcloudyuga/rsvpdata
        ports:
        - containerPort: 5000
